Frontbranch3.0
empathyco/academy-winter-batch-2022 pull request #9
Opened 2022-04-12 11:27 UTC by carmen279

2022-04-12 11:30 UTC, miguelliar commented on blog/frontend/UnitTesting.md
> +#### Participants & Content Deliverers  <!-- (Do not change this line!!!) -->
Delete (my fault, sorry)

2022-04-12 11:31 UTC, miguelliar commented on blog/frontend/UnitTesting.md
> +### [Miguel's Rick & Morty app] (https://github.com/miguelliar/vue-practice)
As there is a blank space that does not perform the link to the repo

2022-04-12 11:32 UTC, miguelliar requested changes
Change the commented lines and we can perform the pull request

2022-04-12 11:32 UTC, miguelliar commented on blog/frontend/UnitTesting.md
> +#### Participants & Content Deliverers  <!-- (Do not change this line!!!) -->
Number line (just in case)

2022-04-12 11:33 UTC, miguelliar commented on blog/frontend/UnitTesting.md
> +#### Participants & Content Deliverers  <!-- (Do not change this line!!!) -->
*Line number 9

2022-04-13 07:10 UTC, carmen279 commented
Changes requested done

2022-04-13 07:18 UTC, merged